---
- hosts: nodes

  vars:
    - my_jenkins_params:
        url_username: admin
        url_password: placeholder
        url: sampleURL
    - oracle_java_version: 8
    - oracle_java_home: "/usr/lib/jvm/java-{{ oracle_java_version }}-oracle"
    - home_path: /home/{{ansible_user}}

  tasks:
    - name: Install required system packages.
      apt: pkg={{ item }} state=present update-cache=yes
      with_items:
        - libmysqlclient-dev
        - python-dev
        - python-pip
        - gcc
        - python-setuptools
        - git-core
        - python-setuptools
      become: yes

    - name: install pyopenssl
      pip:
        name: pyopenssl

    - name: Adding Java ppa
      apt_repository:
        repo: ppa:webupd8team/java
        state: present
      become: yes

    - name: Accept Java license
      debconf: name='oracle-java{{ oracle_java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
      become: yes

    - name: Install Java {{ oracle_java_version }} and set it as default version
      apt:
        name: oracle-java{{ oracle_java_version }}-installer
        state: latest
        cache_valid_time: 3600
        update_cache: yes
      become: yes

    - name: set Java {{ oracle_java_version }} as default version
      apt:
        name: oracle-java{{ oracle_java_version }}-set-default
        state: latest
        update_cache: yes
      become: yes

    - name: upgrade and update the system
      become: yes
      apt:
        upgrade: dist
        update_cache: yes

    - name: Add Jenkins public key
      become: yes
      apt_key:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
        state: present

    - name: Add jenkins repo to the repo/source list
      become: yes
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Install Jenkins package
      become: yes
      apt:
        update_cache: yes
        pkg: jenkins
        state: present


# install jenkins specific packages at remote nodejs
    - name: Install python-jenkins and python-lxml
      become: yes
      apt:
        update_cache: yes
        pkg: "{{item}}"
        state: present
      with_items:
        - python-jenkins
        - python-lxml

    # Set home path for the machine running
    - set_fact:
        home_var: "{{ lookup('env','HOME') }}"

    - name: get admin pass and register it
      shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: admin_pass
      tags:
        - test
      become: yes

    - debug:
        msg: "{{ admin_pass.stdout }}"

    - name: Configure JVM Arguments
      become: yes
      lineinfile:
        dest: /etc/default/jenkins
        regexp: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'

#restarting jenkins service to apply the changes in the config above
    - name: Restart Jenkins
      become: yes
      service:
        name: jenkins
        state: restarted
#
#
# #wait for jenkins to come back
    - name: Wait for Jenkins to start up
      wait_for: timeout=120
      delegate_to: localhost

    - debug:
        var: my_jenkins_params.url_username
      tags:
        - test


    - set_fact:
       new_params: "{{ my_jenkins_params|combine({'url_password':'{{ admin_pass.stdout }}'}, recursive=True) }}"
      tags:
        - test

    - set_fact:
       URL: "http://{{ ansible_ssh_host }}:8080"
      tags:
        - test


    - set_fact:
       new_jenkins_params: "{{ new_params|combine({'url':URL}, recursive=True) }}"
      tags:
        - test

    # Commented out b/c we do not want password to show on console
    - debug:
       var: new_jenkins_params

#install custom in-build available jenkin plugins

    - name: Install jenkin subversion plugin
      jenkins_plugin:
        name: subversion
        params: "{{new_jenkins_params}}"

    - name: Install jenkin github branch source plugin
      jenkins_plugin:
        name: github-branch-source
        params: "{{new_jenkins_params}}"

    - name: Install jenkin ssh-slaves plugin
      jenkins_plugin:
        name: ssh-slaves
        params: "{{new_jenkins_params}}"

    - name: Install jenkin antplugin
      jenkins_plugin:
        name: ant
        params: "{{new_jenkins_params}}"

    - name: Install jenkin workflow-aggregator
      jenkins_plugin:
        name: workflow-aggregator
        params: "{{new_jenkins_params}}"

    - name: Install jenkin pipeline-github-lib
      jenkins_plugin:
        name: pipeline-github-lib
        params: "{{new_jenkins_params}}"

    - name: Install jenkin postbuild task plugin
      jenkins_plugin:
        name: postbuild-task
        params: "{{new_jenkins_params}}"
        with_dependencies: yes

# restart jenkins once plugins are installed

    - name: Restart Jenkins
      become: yes
      service:
        name: jenkins
        state: restarted
      tags:
        - test


#wait for jenkins to come back
    - name: Wait for Jenkins to start up
      wait_for: timeout=120
      delegate_to: localhost
      tags:
        - test


    - name: Downloading Jenkins CLI Jar
      get_url:
        url: "http://{{ansible_ssh_host}}:8080/jnlpJars/jenkins-cli.jar"
        dest: "{{home_path}}/"
        mode: 0755

    - name: Checking Job List For iTrust
      become: true
      shell: "java -jar {{home_path}}/jenkins-cli.jar -s http://{{ ansible_ssh_host }}:8080 list-jobs --username admin --password {{ admin_pass.stdout }}"
      register: job_itrust
      changed_when: "job_itrust.stdout.find('iTrust') == -1"
      tags:
        - test

    - name: Copying itrust.xml
      copy:
        src: itrust.xml
        dest: "{{home_path}}/itrust.xml"
      tags:
        - test

    - name: Create Jenkins iTrust Job Using XML
      become: true
      shell: "java -jar {{home_path}}/jenkins-cli.jar -s http://{{ ansible_ssh_host }}:8080 create-job iTrust < {{home_path}}/itrust.xml --username admin --password {{admin_pass.stdout}}"
      when: "job_itrust.stdout.find('iTrust') == -1"
      tags:
        - test

    - name: Removing iTrust XML file
      file:
        path: "{{home_path}}/itrust.xml"
        state: absent
      tags:
        - test

    - name: Checking Job List For checkbox.io
      become: true
      shell: "java -jar {{home_path}}/jenkins-cli.jar -s http://{{ ansible_ssh_host }}:8080 list-jobs --username admin --password {{ admin_pass.stdout }}"
      register: job_checkbox
      changed_when: "job_checkbox.stdout.find('checkbox.io') == -1"

    - name: Copying Checkbox.io Job XML
      copy:
       src:  checkbox.xml
       dest: "{{home_path}}/checkbox.xml"

    - name: Create Jenkins Jobs for checkbox.io Using XML
      become: true
      shell: "java -jar {{home_path}}/jenkins-cli.jar -s http://{{ ansible_ssh_host }}:8080 create-job checkbox.io < {{home_path}}/checkbox.xml --username admin --password {{admin_pass.stdout}}"
      when: "job_checkbox.stdout.find('checkbox.io') == -1"

    - name: Removing Checkbox.io XML file
      file:
       path: "{{home_path}}/checkbox.xml"
       state: absent
       
    - name: copy useless test detector package.json to jenkins home folder
      copy:
        src: ../UseLessTestDetector/package.json
        dest: "/home/vagrant/package.json"
        mode: 777
      tags:
        - test
        
    - name: copy useless test detector js file to jenkins home folder
      copy:
        src: ../UseLessTestDetector/uselessDetector.js
        dest: "/home/vagrant/uselessDetector.js"
        mode: 777
      tags:
        - test  